# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo See https://aka.ms/yaml
    terraform init
    terraform apply -var-file=envs/$(env).tfvars \ 
      -var subscriptionId=$(subscriptionId) \
      -var tenantId=$(tenantId) \
      -var clientId=$(clientId) \
      -var clientSecret=$(clientSecret) \
      -auto-approve
  displayName: 'Run a multi-line script'
